export const initialArticles = [
  {
    id: 1,
    title: 'Inter-College Basketball Finals This Saturday',
    summary: 'Catch the big game between the North and South colleges at the main gym.',
    content: 'Full article content: details of teams, schedules, ticketing and COVID protocols.',
    category: 'Sports',
    date: '2025-10-12',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80',
    likes: 12,
    comments: [],
  },
  {
    id: 2,
    title: 'Student Art Exhibit Opens Next Week',
    summary: 'A showcase of student work in the Arts Building, featuring paintings and digital media.',
    content: 'Full article: opening reception, participating students, and awards.',
    category: 'Campus Life',
    date: '2025-10-20',
    image: 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?w=800&q=80',
    likes: 34,
    comments: [],
  },
  {
    id: 3,
    title: 'Career Fair: Meet Employers From Top Tech Firms',
    summary: 'Opportunities for internships and full-time roles; bring resumes.',
    content: 'Full article content with company list and registration link.',
    category: 'Events',
    date: '2025-11-05',
    image: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=80',
    likes: 8,
    comments: [],
  },
];
