import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f9fafb" },
  container: { padding: 16, paddingBottom: 100 },
  header: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#111827",
  },
  subHeader: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 6,
    color: "#1e3a8a",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    backgroundColor: "#f9fafb",
  },
  textArea: { minHeight: 120, textAlignVertical: "top" },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: "#f9fafb",
  },
  picker: { height: 50 },
  pickBtn: {
    backgroundColor: "#2563eb",
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    marginVertical: 8,
  },
  pickBtnText: { color: "#fff", fontWeight: "bold" },
  mediaPreview: { alignItems: "center", marginVertical: 8 },
  mediaImage: { width: 230, height: 150, borderRadius: 10 },
  removeBtn: {
    backgroundColor: "#dc2626",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    marginTop: 6,
  },
  removeBtnText: { color: "#fff", fontWeight: "500" },
  btn: {
    backgroundColor: "#e5e7eb",
    padding: 10,
    borderRadius: 8,
    margin: 4,
    flex: 1,
    alignItems: "center",
  },
  primary: { backgroundColor: "#2563eb" },
  success: { backgroundColor: "#16a34a" },
  btnText: { color: "#fff", fontWeight: "bold" },
  row: { flexDirection: "row", justifyContent: "space-between" },
  message: { marginTop: 8, fontWeight: "500", textAlign: "center" },
  gray: { color: "gray" },
  bold: { fontWeight: "600", fontSize: 15 },
  small: { fontSize: 12, color: "gray" },
  link: { color: "#2563eb", fontWeight: "500", marginVertical: 2 },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    marginBottom: 6,
  },
  status: {
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
    fontSize: 12,
    textTransform: "capitalize",
    fontWeight: "600",
  },
  approved: { backgroundColor: "#dcfce7", color: "#166534" },
  rejected: { backgroundColor: "#fee2e2", color: "#7f1d1d" },
  pending: { backgroundColor: "#fef3c7", color: "#78350f" },
  bottomNav: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#fff",
    paddingVertical: 10,
    position: "absolute",
    bottom: 0,
    width: "100%",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 8,
  },
  navItem: { padding: 8, borderRadius: 8 },
  navItemActive: { backgroundColor: "#2563eb" },
  navText: { fontWeight: "bold", color: "#4b5563" },
  navTextActive: { color: "#fff" },
});